# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("Shape of array 1: ", a1.shape)
print("Size of array 1: ", a1.size)
print("Type of array 1: ", type(a1))
print("Dimensions of array 1: ", a1.ndim)

Shape of array 1:  (4,)
Shape of array 2:  (2, 3)
Shape of array 3:  (2, 2, 3)
Size of array 1:  4
Size of array 2:  6
Size of array 3:  12
Type of array 1:  <class 'numpy.ndarray'>
Type of array 2:  <class 'numpy.ndarray'>
Type of array 3:  <class 'numpy.ndarray'>
Dimensions of array 1:  1
Dimensions of array 2:  2
Dimensions of array 3:  3


In [7]:
# Attributes of 2-dimensional array
print("Shape of array 2: ", a2.shape)
print("Size of array 2: ", a2.size)
print("Type of array 2: ", type(a2))
print("Dimensions of array 2: ", a2.ndim)

Shape of array 2:  (2, 3)
Size of array 2:  6
Type of array 2:  <class 'numpy.ndarray'>
Dimensions of array 2:  2


In [8]:
# Attributes of 3-dimensional array
print("Shape of array 3: ", a3.shape)
print("Size of array 3: ", a3.size)
print("Type of array 3: ", type(a3))
print("Dimensions of array 3: ", a3.ndim)

Shape of array 3:  (2, 2, 3)
Size of array 3:  12
Type of array 3:  <class 'numpy.ndarray'>
Dimensions of array 3:  3


In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df1 = pd.DataFrame(a1)

In [11]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0, 100, 3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_1 = np.random.randint(0, 10, size=(7,2))
rand_1

array([[3, 5],
       [7, 4],
       [3, 7],
       [8, 5],
       [9, 1],
       [5, 0],
       [9, 2]])

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_2 = np.random.random((3,5))
rand_2

array([[0.99182126, 0.82310039, 0.05687823, 0.9728063 , 0.06587073],
       [0.05782967, 0.91459653, 0.32904753, 0.16104415, 0.86908333],
       [0.83382457, 0.21343306, 0.84566807, 0.99070558, 0.12387346]])

In [23]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

rand_3 = np.random.randint(0,10,size=(4,6))
rand_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [30]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_4 = np.random.randint(1,10,size=(3,7))

print(rand_4)

# Find the unique numbers in the array you just created
np.unique(rand_4)

[[2 5 8 9 9 1 9]
 [7 9 8 1 8 8 3]
 [1 8 3 3 1 5 7]]


array([1, 2, 3, 5, 7, 8, 9])

In [31]:
# Find the 0'th index of the latest array you created
rand_4[0]

array([2, 5, 8, 9, 9, 1, 9])

In [32]:
# Get the first 2 rows of latest array you created
rand_4[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [33]:
# Get the first 2 values of the first 2 rows of the latest array
rand_4[:2, :2]

array([[2, 5],
       [7, 9]])

In [37]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ones_ar = np.ones((3,5))
rand_5 = np.random.randint(0,10,size=(3,5))
rand_5

array([[0, 2, 4, 2, 0],
       [4, 9, 6, 6, 8],
       [9, 9, 2, 6, 0]])

In [38]:
# Add the two arrays together
rand_5 + ones_ar

array([[ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7.,  9.],
       [10., 10.,  3.,  7.,  1.]])

In [39]:
# Create another array of ones of shape (5, 3)
ones_ar2 = np.ones((5,3))

In [40]:
# Try add the array of ones and the other most recent array together
rand_5 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (10,2) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)


In [41]:
# Subtract the new array of ones from the other most recent array
rand_5 - ones_ar

array([[-1.,  1.,  3.,  1., -1.],
       [ 3.,  8.,  5.,  5.,  7.],
       [ 8.,  8.,  1.,  5., -1.]])

In [42]:
# Multiply the ones array with the latest array
rand_5 * ones_ar

array([[0., 2., 4., 2., 0.],
       [4., 9., 6., 6., 8.],
       [9., 9., 2., 6., 0.]])

In [43]:
# Take the latest array to the power of 2 using '**'
rand_5 ** 2

array([[ 0,  4, 16,  4,  0],
       [16, 81, 36, 36, 64],
       [81, 81,  4, 36,  0]], dtype=int32)

In [44]:
# Do the same thing with np.square()
np.square(rand_5)

array([[ 0,  4, 16,  4,  0],
       [16, 81, 36, 36, 64],
       [81, 81,  4, 36,  0]], dtype=int32)

In [45]:
# Find the mean of the latest array using np.mean()
np.mean(rand_5)

4.466666666666667

In [46]:
# Find the maximum of the latest array using np.max()
np.max(rand_5)

9

In [47]:
# Find the minimum of the latest array using np.min()
np.min(rand_5)

0

In [49]:
# Find the standard deviation of the latest array
np.std(rand_5)

3.263263533472111

In [50]:
# Find the variance of the latest array
np.var(rand_5)

10.648888888888889

In [51]:
# Reshape the latest array to (3, 5, 1)
rand_5.reshape((3,5,1))

array([[[0],
        [2],
        [4],
        [2],
        [0]],

       [[4],
        [9],
        [6],
        [6],
        [8]],

       [[9],
        [9],
        [2],
        [6],
        [0]]])

In [52]:
# Transpose the latest array
rand_5.T

array([[0, 4, 9],
       [2, 9, 9],
       [4, 6, 2],
       [2, 6, 6],
       [0, 8, 0]])

What does the transpose do?

In [54]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ar1 = np.random.randint(0,10,size=(3,3))
ar2 = np.random.randint(0,10,size=(3,2))

In [56]:
# Perform a dot product on the two newest arrays you created
ar1.dot(ar2), ar2.T.dot(ar1)

(array([[164, 112],
        [ 48,  12],
        [133,  80]]),
 array([[164, 104,  85],
        [112,  76,  40]]))

In [57]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ar1 = np.random.randint(0,10,size=(4,3))
ar2 = np.random.randint(0,10,size=(4,3))

In [58]:
# Perform a dot product on the two newest arrays you created
ar1.dot(ar2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [59]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
ar1.T.dot(ar2)

array([[30, 73, 40],
       [14, 56, 28],
       [16, 42, 31]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ar1 = np.random.randint(0,10,size=(3,3))
ar2 = np.random.randint(0,10,size=(3,3))

In [60]:
# Compare the two arrays with '>'
ar1 > ar2

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [61]:
# Compare the two arrays with '>='
ar1 >= ar2

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [62]:
# Find which elements of the first array are greater than 7
ar1 > 7

array([[False, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [63]:
# Which parts of each array are equal? (try using '==')
ar1 == ar2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

In [65]:
# Sort one of the arrays you just created in ascending order
np.sort(ar1)

array([[0, 2, 4],
       [5, 7, 9],
       [3, 7, 8],
       [0, 0, 9]])

In [66]:
# Sort the indexes of one of the arrays you just created
np.argsort(ar1)

array([[1, 2, 0],
       [2, 1, 0],
       [2, 0, 1],
       [0, 1, 2]], dtype=int64)

In [67]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar1)

3

In [68]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar2)

4

In [69]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ar1, axis=1)

array([0, 0, 1, 2], dtype=int64)

In [70]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(ar1, axis=0)

array([1, 2, 3], dtype=int64)

In [74]:
# Create an array of normally distributed random numbers
np.random.uniform(1, 23, size=(3,4))

array([[ 9.77413773, 18.96150121, 18.56359275,  4.31578597],
       [12.18037309, 16.30788175, 19.88389371,  8.17109591],
       [ 5.84530305, 16.64528971, 18.80902302,  8.67065172]])

In [79]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.